### ISSUE TITLE
Version 14.1 is uninstallable

### ISSUE THREAD

**Issue by JuliusBairaktaris** [jigs4wkiller/gapps-plus#1]
The latest Magsik canary can't execute the keycheck module so the installer fails.

Magisk 7e9d4512
Release: 14.1

[magisk_install_log_2021-11-17T09_35_55Z.log](https://github.com/jigs4wkiller/gapps-plus/files/7553026/magisk_install_log_2021-11-17T09_35_55Z.log)

**Comment by jigs4wkiller** [comment]
Fixed, upload in some minutes

**Comment by JuliusBairaktaris** [comment]
The volume key selector error Message loops now but it still won't register anything since it can't find the keycheck module. 

"timeout: can't execute '/data/adb/modules_update/miui-gapps/common/addon/Volume-Key-Selector/tools//keycheck': No such file or directory"

[magisk_install_log_2021-11-17T10_44_09Z.log](https://github.com/jigs4wkiller/gapps-plus/files/7553542/magisk_install_log_2021-11-17T10_44_09Z.log)
